spring:
  application:
    name: product-service
  profiles:
    active: dev

server:
  port: 8081

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    data: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /app/h2

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
