spring:
  profiles:
    active: dev
  jersey:
    application-path: /api
  jackson:
    serialization:
      write_dates_as_timestamps: false
  cloud:
    consul:
      discovery:
        enabled: false

management:
  context-path: /app
  security:
    enabled: false

---
spring:
  profiles: consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        tags: ${spring.application.name},${HOSTNAME:localhost}
        instanceId: ${spring.application.name}-${HOSTNAME:localhost}-${server.port}
        healthCheckPath: ${management.context-path}/health
        healthCheckInterval: 5s

---
spring:
  profiles: dev
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG

