spring:
  application:
    name: cart-service
  profiles:
    active: dev

server:
  port: 8080

rest:
  client:
    config:
      product:
        url: http://product.lvh.me:8081/api
      promotion:
        url: http://promotion.lvh.me:8082/api
