spring:
  application:
    name: cart-service
  profiles:
    active: dev

server:
  port: 8080

rest:
  client:
    config:
      product:
        url: http://product-service.lvh.me:8081/api
      promotion:
        url: http://promotion-service.lvh.me:8082/api

---
spring:
  profiles: haproxy

rest:
  client:
    config:
      # UTL should go through HAProxy
      product:
        url: http://product-service.lvh.me/api
      promotion:
        url: http://promotion-service.lvh.me/api

---
spring:
  profiles: consul

rest:
  client:
    config:
      # UTL should go through HAProxy
      product:
        url: http://product-service.service.consul:8080/api
      promotion:
        url: http://promotion-service.service.consul:8080/api
